# Generated by Django 4.2.4 on 2023-09-06 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("selling_price", models.FloatField()),
                ("discounted_price", models.FloatField()),
                ("description", models.TextField()),
                ("composition", models.TextField(default="")),
                ("prodapp", models.TextField(default="")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("CA", "Campera"),
                            ("FA", "Falda"),
                            ("PU", "Pullover"),
                            ("PA", "Pantalon"),
                            ("SU", "Sueter"),
                            ("ZA", "Zapatillas"),
                            ("TB", "Bordo"),
                            ("TG", "Gris"),
                            ("TV", "Verde"),
                            ("ZB", "Beige"),
                            ("ZR", "Rojo"),
                            ("ZD", "Dorado"),
                        ],
                        max_length=2,
                    ),
                ),
                ("product_image", models.ImageField(upload_to="product")),
            ],
        ),
    ]
