# Generated by Django 4.2.4 on 2023-09-06 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.CharField(
                choices=[
                    ("MJ", "Mujer"),
                    ("HM", "Hombre"),
                    ("ZA", "Zapatillas"),
                    ("TR", "Trajes"),
                    ("TC", "Tacos"),
                ],
                max_length=2,
            ),
        ),
    ]
