# Generated by Django 4.2.4 on 2023-09-08 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("app", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("locality", models.CharField(max_length=200)),
                ("city", models.CharField(max_length=50)),
                ("mobile", models.IntegerField(default=0)),
                ("zipcode", models.IntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("Buenos Aires", "Buenos Aires"),
                            ("Catamarca", "Catamarca"),
                            ("Chaco", "Chaco"),
                            ("Chubut", "Chubut"),
                            ("Córdoba", "Córdoba"),
                            ("Corrientes", "Corrientes"),
                            ("Entre Ríos", "Entre Ríos"),
                            ("Formosa", "Formosa"),
                            ("Jujuy", "Jujuy"),
                            ("La Pampa", "La Pampa"),
                            ("La Rioja", "La Rioja"),
                            ("Mendoza", "Mendoza"),
                            ("Misiones", "Misiones"),
                            ("Neuquén", "Neuquén"),
                            ("Río Negro", "Río Negro"),
                            ("Salta", "Salta"),
                            ("San Juan", "San Juan"),
                            ("San Luis", "San Luis"),
                            ("Santa Cruz", "Santa Cruz"),
                            ("Santa Fe", "Santa Fe"),
                            ("Santiago del Estero", "Santiago del Estero"),
                            ("Tierra del Fuego", "Tierra del Fuego"),
                            ("Tucumán", "Tucumán"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
